/**
 * Replays the SEC-2291 credential-stuffing campaign against whatever code is
 * currently in src/auth.ts.
 *
 * This is a real measurement of `issueToken`, not a fixture: IncidentOS runs
 * it once before the patch and once after, and the numbers it reports are
 * the ones shown in the verification panel — mirroring how
 * scripts/memory-sim.ts measures src/transactions.ts.
 *
 * The six source addresses and their attempt totals mirror
 * demo-data/security/sources.json (generated by scripts/generate-attack-data.ts).
 * They are inlined here, not read from disk, because this script runs inside
 * the agent's sandbox copy of the repository, which only contains
 * payments-api — it cannot see demo-data/.
 *
 * Run with:  node --import tsx scripts/attack-sim.ts
 * Output:    a single line of JSON on stdout.
 */
import { getActiveSessionCount, issueToken, resetAuthState } from "../src/auth.js";

/** Deterministic PRNG (mulberry32), seeded apart from the demo-data generator. */
function rng(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(42017);

// Mirrors demo-data/security/sources.json; the sandbox cannot see demo-data.
// Attempt totals are the real fixture values, so the sum below lands exactly
// on campaign.json's totals.maliciousAttempts (4,548).
const SOURCES = [
  { ip: "185.220.101.47", country: "NL", attempts: 1182 },
  { ip: "45.133.216.18", country: "RO", attempts: 955 },
  { ip: "103.251.167.92", country: "HK", attempts: 819 },
  { ip: "194.26.229.174", country: "RU", attempts: 637 },
  { ip: "141.98.11.203", country: "LT", attempts: 500 },
  { ip: "89.248.165.31", country: "SC", attempts: 455 },
];

const TOTAL_ATTEMPTS = SOURCES.reduce((sum, s) => sum + s.attempts, 0);

// Real breach-corpus matches, per demo-data/security/campaign.json.
const REAL_HITS = [
  { account: "ops-runner@northwind.example", password: "Trellis-Cobalt-42", minuteOffset: 19 }, // 14:24
  { account: "billing-svc@northwind.example", password: "Qu1llFerry-Batch9", minuteOffset: 22 }, // 14:27
  { account: "a.okafor@northwind.example", password: "HarborKite!7v", minuteOffset: 24 }, // 14:29
];

// A spray of mostly-nonexistent accounts, standing in for the wider breach
// corpus the campaign tries against every target.
const FAKE_ACCOUNTS = [
  "j.smith@northwind.example",
  "a.brown@northwind.example",
  "r.kowalski@northwind.example",
  "t.nakamura@northwind.example",
  "l.fontaine@northwind.example",
  "p.singh@northwind.example",
  "e.moreau@northwind.example",
  "c.hoffmann@northwind.example",
  "n.dubois@northwind.example",
  "y.tanaka@northwind.example",
  "b.ferreira@northwind.example",
  "h.aoyama@northwind.example",
  "svc-reporting@northwind.example",
  "svc-payroll@northwind.example",
  "svc-backup@northwind.example",
  "admin@northwind.example",
  "root@northwind.example",
  "support@northwind.example",
  "g.ibrahim@northwind.example",
  "w.chen@northwind.example",
  "f.oduya@northwind.example",
  "m.santos@northwind.example",
  "q.zhao@northwind.example",
  "v.petrov@northwind.example",
  "d.osei@northwind.example",
  "k.abbas@northwind.example",
  "u.becker@northwind.example",
  "x.leclerc@northwind.example",
  "z.hassan@northwind.example",
  "o.wren@northwind.example",
  "i.molnar@northwind.example",
  "s.oyelaran@northwind.example",
];

const WRONG_GUESSES_BEFORE_HIT = 65;

// Spacing per source, comfortably under PER_IP_LIMIT (30) per AUTH_WINDOW_MS
// (60s): ~27 attempts/min, which keeps the per-IP throttle from ever firing.
const INTERVAL_MS = 2_200;

const SIM_START = Date.UTC(2026, 2, 11, 14, 5, 0); // 2026-03-11T14:05:00Z

interface Slot {
  ip: string;
  timestamp: number;
}

// Build each source's own timeline, then merge into one chronological list.
const slots: Slot[] = [];
for (const source of SOURCES) {
  for (let i = 0; i < source.attempts; i++) {
    slots.push({ ip: source.ip, timestamp: SIM_START + i * INTERVAL_MS });
  }
}
slots.sort((a, b) => a.timestamp - b.timestamp);

// Pick, for each real hit, the earliest global slot at or after its target
// simulated minute. Reserve the WRONG_GUESSES_BEFORE_HIT slots immediately
// before it (chronologically) to carry wrong-password guesses against that
// same account, guaranteeing the hit is preceded by enough failures.
interface Assignment {
  account: string;
  password: string;
}
const assignments = new Map<number, Assignment>();

for (const hit of REAL_HITS) {
  const targetTime = SIM_START + hit.minuteOffset * 60_000;
  const hitIndex = slots.findIndex((s) => s.timestamp >= targetTime);
  if (hitIndex < WRONG_GUESSES_BEFORE_HIT) {
    throw new Error(`not enough traffic before the ${hit.account} hit to seed prior failures`);
  }
  assignments.set(hitIndex, { account: hit.account, password: hit.password });
  for (let i = hitIndex - WRONG_GUESSES_BEFORE_HIT; i < hitIndex; i++) {
    assignments.set(i, { account: hit.account, password: "wrong-password" });
  }
}

function randomFakeAccount(): string {
  return FAKE_ACCOUNTS[Math.floor(rand() * FAKE_ACCOUNTS.length)];
}

resetAuthState();

let rateLimited = 0;
let attemptsReachingVerifier = 0;
const realResults = new Map<string, ReturnType<typeof issueToken>>();

for (let i = 0; i < slots.length; i++) {
  const slot = slots[i];
  const reserved = assignments.get(i);
  const account = reserved ? reserved.account : randomFakeAccount();
  const password = reserved ? reserved.password : "wrong-password";

  const result = issueToken({
    account,
    password,
    remoteAddress: slot.ip,
    receivedAt: slot.timestamp,
  });

  if (!result.ok && result.reason === "rate_limited") {
    rateLimited++;
  } else {
    attemptsReachingVerifier++;
  }

  if (reserved && reserved.password !== "wrong-password") {
    realResults.set(reserved.account, result);
  }
}

const credentialsMatched = [...realResults.values()].filter(
  (r) => r.ok || (!r.ok && r.reason === "mfa_required"),
).length;

const sessionsCreated = getActiveSessionCount();

// An account counts as "locked" only if its correct-password attempt was
// rejected for a reason that is neither rate limiting nor an ordinary MFA
// challenge — both of those are expected, non-lockout outcomes for a correct
// password. A real per-account lockout instead intercepts before password
// verification even resolves to "mfa_required", so a fixed auth.ts reports
// some other reason (e.g. "invalid_credentials") once an account is locked.
const lockedAccounts = REAL_HITS.filter((hit) => {
  const result = realResults.get(hit.account);
  return result && !result.ok && result.reason !== "rate_limited" && result.reason !== "mfa_required";
}).length;

process.stdout.write(
  JSON.stringify({
    attempts: TOTAL_ATTEMPTS,
    sources: SOURCES.length,
    rateLimited,
    attemptsReachingVerifier,
    credentialsMatched,
    sessionsCreated,
    lockedAccounts,
  }) + "\n",
);
